from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """
    Represents a response from the chat service.
    """

    message: str = Field(
        ...,
        description="The chat message generated by the AI in response to the user's input.",
    )

    summarized_context: str = Field(
        ...,
        description="A brief summary of the previous conversation, to provide relevant context for the next user message.",
    )
